before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: SFwqL1ANbUDzsF4Ttbz/I/UNGzUF2YnRTKVLunIXBvDcuYNmuL9NCcqFdXypkH1xcnW/G97/treFlzomhiXQCA9Sco7PFftAWORywxAUV3+T+0gc7hxxphjGHxpthd7ND0RIGWVyfvEtkTjm0XagGBih3/YTdUtKh1eXskver/ghZCeP8nWb1fKVUZgWNA0apbl+Q4wMLGnfy5fgJow8FYMBcNjdHRu7nxqs9Q3w1M/pqWVSV/MXrpT2NbeeB+MMWFXtOnqZV8VilQRpkgIgeT8EHWfquOsTGLyEY7BIQiZj51u3CcReiWjO7+9Up+C6yWV84L3LW2lvHPz3xTpSTjYWhOya3GRiW8SPzTalLlTsCJNjTvruqC/5YA2QXOidfcgT8fZyApIMJKDRc5yAUhmb/lr1UrHUJbqKMsrRb2MaD0u68YT9EkNCAgIXoXWNUE16ekvDf4rAOmKP5orHBCw8toqs6RaRXY1h8O0V03hzz/vAFOFOWpBxTcpwgjXo7qh53AjwCicKSa4gw2NZxCGFtSgnoDggj9hC8OtgN+WIUMSUesznPbeuZx2pjVmBWji86FreHwW3c8CjRP6or81d7ph8bEviwqNIRmxiBF3g6IgF4IkvpPA9UPkKNWngRwyJFw0hke7a9uquP9RPH31L96w08yQ3tNIDbrJQA0o= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
